### ISSUE TITLE
ODT Export throwing HTTP 500 error

### ISSUE THREAD

**Issue by spricer** [lpaulsen93/dokuwiki-plugin-odt#266]
Combination of WRAP's **important/warning/info** tags and **ordered list** is throwing HTTP 500 Error.
To reproduce use next:
- Create article with next entry:
`  - <WRAP important> some text </WRAP>`
- Export article by using **ODT Export** extension

**Env:**
- PHP (php-fpm) 7.4.16
- Nginx 1.19.8
- RHEL 7.9
- Current dokuwiki and plugins

**Template**: sprintdoc

Error

```
2021/06/04 15:13:37 [error] 19816#19816: *4299 FastCGI sent in stderr: "PHP message: PHP Warning:  preg_match(): Empty regular expression in /usr/share/nginx/dokuwiki/lib/plugins/wrap/helper.php on line 83PHP message: PHP Warning:  preg_match(): Empty regular expression in /usr/share/nginx/dokuwiki/lib/plugins/wrap/helper.php on line 83PHP message: PHP Warning:  preg_match(): Empty regular expression in /usr/share/nginx/dokuwiki/lib/plugins/wrap/helper.php on line 83PHP message: PHP Warning:  preg_match(): Empty regular expression in /usr/share/nginx/dokuwiki/lib/plugins/wrap/helper.php on line 83PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method ODTElementParagraph::getListLastParagraphPosition() in /usr/share/nginx/dokuwiki/lib/plugins/odt/ODT/ODTList.php:57
Stack trace:
#0 /usr/share/nginx/dokuwiki/lib/plugins/odt/ODT/ODTDocument.php(1021): ODTList::listClose()
#1 /usr/share/nginx/dokuwiki/lib/plugins/odt/ODT/ODTTable.php(93): ODTDocument->listClose()
#2 /usr/share/nginx/dokuwiki/lib/plugins/odt/ODT/ODTTable.php(421): ODTTable::tableOpen()
#3 /usr/share/nginx/dokuwiki/lib/plugins/odt/ODT/ODTDocument.php(1200): ODTTable::tableOpenUseProperties()
#4 /usr/share/nginx/dokuwiki/lib/plugins/odt/renderer/page.php(1815): ODTDocument->tableOpenUseProperties()
#5 /usr/share/nginx/dokuwiki/lib/plugins/wrap/helper.php(727): renderer_plugin_odt_page->_odtTableOpenUseProperties()
#6 /usr/share/nginx/dokuwiki/lib/plugins/wrap/helper.php(204): helper_plugin_wrap->renderODTOpenTable()
#7 /usr/share/nginx/dokuwiki/lib/plugins/wrap/syntax/div.php(126): helper_plugin_wrap->renderODTEle" while reading response header from upstream, client: 192.168.1.15, server: dokuwikidemo.com, request: "GET /doku.php?id=playground:playground&do=export_odt HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm/dokuwiki.sock:", host: "dokuwikidemo.com", referrer: "https://dokuwikidemo.com/doku.php?id=playground:playground"
```

**Comment by spricer** [comment]
After further reading this is probably duplicate of #254.
Funny thing is that in other  dokuwiki installation I have with newer redhat 8.3 this error does not show up even with only getCurrent() on line 54!
Versions of components are similar except OS.
