### ISSUE TITLE
[ERROR] E_WARNING: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by dexter74** [lpaulsen93/dokuwiki-plugin-odt#316]
Hello,

Can your fix problem.

**Release**

```
2023-04-04a "Jack Jackrum"
```

**Log**
```
cat ./dokuwiki/data/log/error/2024-02-27.log
2024-02-27 16:58:09     /srv/dokuwiki/lib/plugins/move/action/rename.php(42)    E_WARNING: Trying to access array offset on value of type null
  #0 /srv/dokuwiki/lib/plugins/move/action/rename.php(42): dokuwiki\ErrorHandler::errorHandler()
  #1 /srv/dokuwiki/inc/Extension/EventHandler.php(80): action_plugin_move_rename->handle_init()
  #2 /srv/dokuwiki/inc/Extension/Event.php(96): dokuwiki\Extension\EventHandler->process_event()
  #3 /srv/dokuwiki/inc/Extension/Event.php(136): dokuwiki\Extension\Event->advise_after()
  #4 /srv/dokuwiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
  #5 /srv/dokuwiki/doku.php(120): dokuwiki\Extension\Event::createAndTrigger()
  #6 {main}
```

**Comment by eduardomozart** [comment]
This Issue doesn't seem to be related to this plug-in. Please close it. @Klap-in can you close it?
