### ISSUE TITLE
cant use css file

### ISSUE THREAD

**Issue by wittsolutionsgmbh** [lpaulsen93/dokuwiki-plugin-odt#328]
Hello,
i wanted to export my page with a css template with the following command onsite: {{odt>odt_template:standard.css}}.
yes i create a sub under root as :odt aswell.

When i try to export it gives me this error: 
"typeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the odt plugin."

Dokuwiki error log: (xxxx is on purpose for security reasons)
2024-11-08 13:11:19
E_WARNING: fopen(/var/www/dokuwiki/data/tmp/odt/xxxx/manifest.xml): Failed to open stream: No such file or directory
/var/www/dokuwiki/lib/plugins/odt/ODT/ODTExport.php(275)
#0 [internal function]: dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/dokuwiki/lib/plugins/odt/ODT/ODTExport.php(275): fopen()
#2 /var/www/dokuwiki/lib/plugins/odt/ODT/ODTExport.php(233): ODTExport::replaceInFile()
#3 /var/www/dokuwiki/lib/plugins/odt/ODT/ODTExport.php(257): ODTExport::buildFromODTTemplate()
#4 /var/www/dokuwiki/lib/plugins/odt/ODT/ODTDocument.php(805): ODTExport::buildZIPFile()
#5 /var/www/dokuwiki/lib/plugins/odt/renderer/page.php(323): ODTDocument->getODTFileAsString()
#6 /var/www/dokuwiki/lib/plugins/odt/renderer/page.php(288): renderer_plugin_odt_page->finalize_ODTfile()
#7 /var/www/dokuwiki/inc/parserutils.php(691): renderer_plugin_odt_page->document_end()
#8 /var/www/dokuwiki/inc/parserutils.php(158): p_render()
#9 /var/www/dokuwiki/inc/Action/Export.php(93): p_cached_output()
#10 /var/www/dokuwiki/inc/ActionRouter.php(86): dokuwiki\Action\Export->preProcess()
#11 /var/www/dokuwiki/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction()
#12 /var/www/dokuwiki/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
#13 /var/www/dokuwiki/inc/actions.php(19): dokuwiki\ActionRouter::getInstance()
#14 /var/www/dokuwiki/doku.php(131): act_dispatch()
#15 {main}
2024-11-08 13:11:19
TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given
/var/www/dokuwiki/lib/plugins/odt/ODT/ODTExport.php(276)
#0 /var/www/dokuwiki/lib/plugins/odt/ODT/ODTExport.php(276): fwrite()
#1 /var/www/dokuwiki/lib/plugins/odt/ODT/ODTExport.php(233): ODTExport::replaceInFile()
#2 /var/www/dokuwiki/lib/plugins/odt/ODT/ODTExport.php(257): ODTExport::buildFromODTTemplate()
#3 /var/www/dokuwiki/lib/plugins/odt/ODT/ODTDocument.php(805): ODTExport::buildZIPFile()
#4 /var/www/dokuwiki/lib/plugins/odt/renderer/page.php(323): ODTDocument->getODTFileAsString()
#5 /var/www/dokuwiki/lib/plugins/odt/renderer/page.php(288): renderer_plugin_odt_page->finalize_ODTfile()
#6 /var/www/dokuwiki/inc/parserutils.php(691): renderer_plugin_odt_page->document_end()
#7 /var/www/dokuwiki/inc/parserutils.php(158): p_render()
#8 /var/www/dokuwiki/inc/Action/Export.php(93): p_cached_output()
#9 /var/www/dokuwiki/inc/ActionRouter.php(86): dokuwiki\Action\Export->preProcess()
#10 /var/www/dokuwiki/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction()
#11 /var/www/dokuwiki/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
#12 /var/www/dokuwiki/inc/actions.php(19): dokuwiki\ActionRouter::getInstance()
#13 /var/www/dokuwiki/doku.php(131): act_dispatch()
#14 {main}

if anyone has a solutions lmk

**Comment by Chris75forumname** [comment]
I can confirm, what you described. I couldn't get it to work either.

Jack Jackrum (on-USB-stick), newest plugin version

Config options:

    plugin»odt»tpl_dir: odt
    plugin»odt»odt_template: template.css
    plugin»odt»css_usage: off (plugins only)
    mime.conf: css text/css
    inpage: {{odt>template:template.css}}

I get the output: PK#################### in the odt file, that is generated.
